//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DistributionLists
{    
    private DistributionList[] _distributionListArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DistributionList", IsNullable=false)]
    public DistributionList[] DistributionListArray
	{
        get => _distributionListArrayField;
        set => _distributionListArrayField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DistributionList
{    
    private DistributionListItem[] _distributionListItemsField;
    
    private string _nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DistributionListItem")]
    public DistributionListItem[] DistributionListItems
	{
        get => _distributionListItemField;
        set => _distributionListItemField = value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DistributionListName
	{
        get => _nameField;
        set => _nameField = value;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DistributionListItem {
    
    private string _addressBookEntryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AddressBookEntry {
        get {
            return _addressBookEntryField;
        }
        set {
            _addressBookEntryField = value;
        }
    }
}
