//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.Diagnostics;
using Windows.Storage;
using MetroLog;

namespace PacketMessaging
{

	// 
	// This source code was auto-generated by xsd, Version=4.0.30319.33440.
	// 


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	//[System.SerializableAttribute()]
	//[System.Diagnostics.DebuggerStepThroughAttribute()]
	//[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ProfileArray
	{
		private ILogger log = LogManagerFactory.DefaultLogManager.GetLogger<ProfileArray>();

		static string profileFileName = "Profiles.xml";

		private Profile[] profileField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Profile")]
		public Profile[] Profiles
		{
			get
			{
				return this.profileField;
			}
			set
			{
				this.profileField = value;
			}
		}

		public static async Task<ProfileArray> OpenAsync(StorageFolder localFolder)
		{
			ProfileArray profileArray = null;
			StorageFile file = null;
			try
			{
				var storageItem = await localFolder.TryGetItemAsync(profileFileName);
                if (storageItem == null)
                {
                    // Create a new profile file with a default entry
                    Profile profile = new Profile()
                    {
                        Name = "Default",
                        BBS = ViewModels.SharedData.SharedDataInstance.BbsArray.BBSDataArray[0].Name,
                        TNC = ViewModels.SharedData.SharedDataInstance.TncDeviceArray.TNCDevices[0].Name,
                        SendTo = "",
                        Selected = true
                    };

					profileArray = new ProfileArray();
					Profile[] profiles = new Profile[1];
					profiles.SetValue(profile, 0);
					profileArray.Profiles = profiles;

					profileArray.Save(localFolder.Path);
				}

				file = await localFolder.GetFileAsync(profileFileName);

				using (FileStream reader = new FileStream(file.Path, FileMode.Open))
				{
					XmlSerializer serializer = new XmlSerializer(typeof(ProfileArray));
					profileArray = (ProfileArray)serializer.Deserialize(reader);
				}
			}
			catch (Exception e)
			{
				Debug.WriteLine ($"Error opening file {file?.Path + profileFileName}, {e}");
			}

			return profileArray;
		}


		public void Save(string filePath)
		{
			try
			{
				using (StreamWriter writer = new StreamWriter(new FileStream(filePath + @"\" + profileFileName, FileMode.Create)))
				{
					XmlSerializer serializer = new XmlSerializer(typeof(ProfileArray));
					serializer.Serialize(writer, this);
				}
			}
			catch (Exception e)
			{
				log.Error($"Error saving file {filePath + profileFileName}, {e}");
			}
		}

		public async Task SaveAsync()
		{
			StorageFolder localFolder = ApplicationData.Current.LocalFolder;
			try
			{
				var storageItem = await localFolder.TryGetItemAsync(profileFileName);
				if (storageItem != null)
				{
					using (Stream writer = new FileStream(storageItem.Path, FileMode.Create))
					{
						XmlSerializer serializer = new XmlSerializer(typeof(ProfileArray));
						serializer.Serialize(writer, this);
					}
				}
				else
				{
					log.Error($"File not found {profileFileName}");
				}
			}
			catch (Exception e)
			{
				log.Error($"Error saving file {profileFileName}, {e}");
			}
		}

	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
	//[System.SerializableAttribute()]
	//[System.Diagnostics.DebuggerStepThroughAttribute()]
	//[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class Profile
	{

		private string nameField;

		private string tNCField;

		private string bBSField;

		private string sendToField;

		private bool selectedField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string TNC
		{
			get
			{
				return this.tNCField;
			}
			set
			{
				this.tNCField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string BBS
		{
			get
			{
				return this.bBSField;
			}
			set
			{
				this.bBSField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string SendTo
		{
			get
			{
				return this.sendToField;
			}
			set
			{
				this.sendToField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool Selected
		{
			get
			{
				return this.selectedField;
			}
			set
			{
				this.selectedField = value;
			}
		}

		public override string ToString() => Name;
	}
}
